FROM docker.io/zenika/alpine-chrome:latest

USER root

# Install chrome extension from URL and place it in /opt
RUN apk add --no-cache curl unzip

RUN mkdir -p /usr/src/app/extensions/adblock /etc/chromium/policies/managed /etc/chromium/policies/recommended

ADD https://gitlab.com/eyeo/browser-extensions-and-premium/extensions/extensions/-/releases/adblock-6.33.5/downloads/adblock-chrome-6.33.5-mv3.zip /tmp/extension.zip

RUN unzip /tmp/extension.zip -d /usr/src/app/extensions/adblock && rm /tmp/extension.zip

RUN chown -R chrome:chrome /usr/src/app

# Run Chrome as non-privileged
USER chrome
WORKDIR /usr/src/app

ENV CHROME_BIN=/usr/bin/chromium-browser 
ENV CHROME_PATH=/usr/lib/chromium/
ENTRYPOINT ["chromium-browser"]
CMD ["--headless", "--disable-dev-shm-usage", "--disable-gpu", "--disable-sync", "--hide-scrollbars", "--load-extension=/usr/src/app/extensions/adblock", "--no-first-run", "--no-sandbox", "--remote-debugging-address=0.0.0.0", "--remote-debugging-port=9222", "--window-size=1280,720", "--ozone-platform=headless", "--password-store=basic", "--use-mock-keychain", "--disable-features=UseDBus"]
