# Mosquitto / MQTT configuration file

## General
persistence true
persistence_location /mosquitto/data
user mosquitto
listener 1883
listener 0 /mosquitto/data/mosquitto.sock
pid_file /mosquitto/data/mosquitto.pid

## Security
allow_anonymous true
password_file /mosquitto/config/credentials.conf

## Logging
log_dest stdout
