FROM docker.io/haproxytech/haproxy:alpine-s6-3.4

USER root

RUN mkdir -p /run/haproxy /etc/ssl/certs /etc/ssl/certs/external /var/lib/haproxy/certs

RUN chown -R haproxy:haproxy /run/haproxy

RUN mv /tmp/dataplaneapi /usr/local/sbin && chmod +x /usr/local/sbin/dataplaneapi && chown root:root /usr/local/sbin/dataplaneapi

RUN haproxy -vv
